#!/bin/bash
# init
function pause(){
   read -p "$*"
}

PORTLEFT=$1
PORTRIGHT=$3
ZOOM=$3

DIRLEFT=left
DIMENSIONSLEFT=640x800
DIRRIGHT=right
DIMENSIONSRIGHT=640x800+640+0

# create the directories
mkdir captures/$DIRLEFT captures/$DIRRIGHT -p
cd captures
# config left
gphoto2 --set-config zoom=$ZOOM --port=$PORTLEFT
gphoto2 --set-config whitebalance=3 --port=$PORTLEFT
# config right
gphoto2 --set-config zoom=$ZOOM --port=$PORTRIGHT
gphoto2 --set-config whitebalance=3 --port=$PORTRIGHT

echo "Starting camera left";
nohup gphoto2 --capture-image-and-download --interval=-1 --filename=$DIRLEFT/%04n.%C --port=$PORTLEFT&
PIDLEFT=$!

# right
echo "Starting camera right";
nohup gphoto2 --capture-image-and-download --interval=-1 --filename=$DIRLEFT/%04n.%C --port=$PORTRIGHT&
PIDRIGHT=$!

while true; do
	pause 'Press [Enter] key to capture...'
	kill -USR1 $PIDLEFT $PIDRIGHT	
done

