#!/bin/bash
# init
function pause(){
   read -p "$*"
}

PORTLEFT=$1
PORTRIGHT=$2
ZOOM=$3

DIRLEFT=images/left
DIMENSIONSLEFT=640x800
DIRRIGHT=images/right
DIMENSIONSRIGHT=640x800+640+0

#clear the directories
rm $DIRLEFT/* $DIRRIGHT/*
# create the directories
mkdir $DIRLEFT $DIRRIGHT -p
# config left
gphoto2 --set-config zoom=$ZOOM --port "$PORTLEFT"
gphoto2 --set-config whitebalance=3 --port "$PORTLEFT"
# config right
gphoto2 --set-config zoom=$ZOOM --port "$PORTRIGHT"
gphoto2 --set-config whitebalance=3 --port "$PORTRIGHT"

echo "Starting camera left";
nohup gphoto2 --capture-image-and-download --interval=-1 --filename $DIRLEFT/%04n.%C --port "$PORTLEFT" --force-overwrite&
PIDLEFT=$!

# right
echo "Starting camera right";
nohup gphoto2 --capture-image-and-download --interval=-1 --filename $DIRRIGHT/%04n.%C --port "$PORTRIGHT" --force-overwrite&
PIDRIGHT=$!

while true; do
	pause 'Press [Enter] key to capture...'
	kill -USR1 $PIDLEFT
#	sleep 2
	nohup feh $DIRLEFT -nxZ. -g $DIMENSIONSLEFT&
	nohup feh $DIRRIGHT -nxZ. -g $DIMENSIONSRIGHT&
#	sleep 2
	killall -q feh
	
done
